id: 0b76557165094b49a21d5c455c492781
title: Toh_679-Dharan%C4%AB_Praising_the_Qualities_of_the_Immeasurable_One-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-091-077
  eft-text-version: 1.1.2 2020
